[homework#9]-js-part-4 by Roman Ivashkevich
qaprosoft/devlaba01 pull request #111
Opened 2021-04-16 12:22 UTC by emarf

2021-04-16 16:43 UTC, danymill commented on homeworks/roman-ivashkevich/09-js-basic/Serialized.js
> +            if (value !== this.constructor.name) {
you can join 2 `if`s

2021-04-18 11:24 UTC, DmitryMishin requested changes

2021-04-18 11:24 UTC, DmitryMishin commented on homeworks/roman-ivashkevich/09-js-basic/Serialized.js
> +    console.log(this.constructor.name);
remove console.log from production code 😉

2021-04-18 11:24 UTC, DmitryMishin commented on homeworks/roman-ivashkevich/09-js-basic/Serialized.js
> +// console.log(new Post().wakeFrom(serialized)); // Error: Impossible to wake up from this value of serialized. Class name does not match.
remove comments that you don't use

2021-04-21 20:29 UTC, DmitryMishin approved these changes

2021-04-21 20:29 UTC, merged