[homework#12]-js-basics by Roman Ivashkevich
qaprosoft/devlaba01 pull request #150
Opened 2021-04-27 12:16 UTC by emarf

2021-04-27 12:19 UTC, emarf commented
![image](https://user-images.githubusercontent.com/55133404/116239942-ecbbc500-a76b-11eb-8929-2f0724024930.png)

![image](https://user-images.githubusercontent.com/55133404/116239897-dd3c7c00-a76b-11eb-9acf-da949e6c6a03.png)

2021-05-12 07:22 UTC, danymill requested changes

2021-05-12 07:22 UTC, danymill commented on homeworks/roman-ivashkevich/12-js-basic/script.js
> +const binarySearch = (data, id) => {
something wrong with it
![image](https://user-images.githubusercontent.com/6594800/117934916-d4bb7800-b30b-11eb-8cb0-8aaa2768bba5.png)

2021-05-17 05:33 UTC, danymill requested changes

2021-05-17 05:33 UTC, danymill commented on homeworks/roman-ivashkevich/12-js-basic/script.js
> +const quickSort = (arr) => {
Doesn't work properly
![image](https://user-images.githubusercontent.com/6594800/118437037-8979de80-b6ea-11eb-9f81-62418b0cedaa.png)

2021-05-17 12:57 UTC, merged