[homework#18]-react-class-and-functional components by Ilya Ischenko
qaprosoft/devlaba01 pull request #206
Opened 2021-06-05 11:35 UTC by ilya07092000

2021-06-14 20:31 UTC, esvyridov requested changes

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +                  onClick={this.refreshCard.bind(this, index)}
all binding should be done in `constructor` to avoid re-binding a function on each re-render. Using arrow functions can help you to avoid using `.bind` at all. If you have to pass some arguments to the `refreshCard` function simply use `onClick={() => this.refreshCard(index)}` or call `onClick` prop inside `Card` component with `index` which you have to pass additionally into to `Card` component

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +              <AddBtn onClick={() => this.addCard()} />
`onClick` prop can be re-written to `onClick={this.addCard`}

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +                <Button onClick={() => this.refreshAll()}>Refresh All</Button>
Same thing with `onClick` prop

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +    this.getRandomCard().then((card) => {
The `App` component would be much better if only promises or only async / await syntax was used inside. But not I see both styles

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +    const radnomNumber = Math.floor(cards.length * Math.random());
typo

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +    const res = await data.json();
`res` can be avoided by `return await data.json()`

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +    const res = await data.json();
By the way `fetch` returns `Response` interface so it make sense to use names of the constants vice versa like
```
const res = await fetch('https://tinyfac.es/api/users');
const data = await data.json();
```

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +      oldCards.splice(index, 1, cards[0]);
I think you manipulate with the state directly here

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +    fetchedCards: [],
I think it can be named just `cards`, not sure about `fetched` prefix

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +    loader: false,
usually loading state can be named like `isLoading` or `isPending`.

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/Components/Button/Button.jsx
> +      <>
Fragment can be omitted

2021-06-14 20:31 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/Components/Card/Card.jsx
> +          onClick={(index) => this.props.onClick(index)}
`e` (event) is called as `index` for some reason

2021-06-14 20:51 UTC, esvyridov requested changes

2021-06-14 20:51 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/Components/Card/Card.jsx
> +            <img className="refresh__icon" src={refresfIcon} />
typo

2021-06-14 20:51 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/Components/AddBtn/AddBtn.jsx
> +      <div className="add-btn">
the `button` should be used together with `props.onClick` instead of  clickable `div`

2021-06-15 09:52 UTC, ilya07092000 commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/App.js
> +              <AddBtn onClick={() => this.addCard()} />
I think it can not be re-written because of context, I use "this" in addCard function

2021-06-15 10:27 UTC, ilya07092000 commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/Components/AddBtn/AddBtn.jsx
> +      <div className="add-btn">
Thanks for review!

2021-06-15 21:57 UTC, esvyridov approved these changes

2021-06-15 21:57 UTC, esvyridov commented on homeworks/ilya-ischenko/18-react-class-and-functional-components/app/src/Components/AddBtn/AddBtn.jsx
> +      <div className="add-btn">
Everything looks great but this component should have button inside

2021-06-20 10:14 UTC, merged