[homework#23]-BE-1-intro by Darya Shimanskaya
qaprosoft/devlaba01 pull request #243
Opened 2021-07-07 15:38 UTC by vastya

2021-07-08 13:35 UTC, shov commented on homeworks/darya-shimanskaya/23-BE-1-intro/server.js
> +  process.env.PORT = (fs.readFileSync('./.env')).toString().split(':')[1].trim()
.env files usually use =
we cannot be sure that .env contains PORT only

2021-07-12 15:15 UTC, DmitryMishin requested changes

2021-07-12 15:15 UTC, DmitryMishin commented on homeworks/darya-shimanskaya/23-BE-1-intro/server.js
> +const server = http.createServer(  (req, res) => {
please remove 2 spaces

2021-07-12 15:15 UTC, DmitryMishin commented on homeworks/darya-shimanskaya/23-BE-1-intro/server.js
> +    res.end("page not found")
use either single quotes or double quotes

2021-07-12 15:15 UTC, DmitryMishin commented on homeworks/darya-shimanskaya/23-BE-1-intro/server.js
> +server.listen( PORT, 'localhost', () => {
are you sure you need this space?

2021-07-12 15:17 UTC, DmitryMishin commented on homeworks/darya-shimanskaya/23-BE-1-intro/server.js
> +    res.writeHead(200, {'Content-Type': 'text/js'});
remove the semicolon here and in a few more places or add them everywhere

2021-07-15 08:38 UTC, merged