[homework#3] HTML-CSS by Mariana Dzividzinska
qaprosoft/devlaba01 pull request #39
Opened 2021-03-18 11:52 UTC by DzividzinskaM

First task result:
![image](https://user-images.githubusercontent.com/45274002/111621484-b85dfc00-87f0-11eb-9a9d-ae66ffebacd3.png)

Second task result: 
![image](https://user-images.githubusercontent.com/45274002/111621823-18ed3900-87f1-11eb-81e6-3097d985bb0f.png)

2021-03-21 19:55 UTC, danymill requested changes

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/index.html
> +                    <h1 class="title">Portfolio</h1>
Only one `<h1>` tag containing the main page title should be on the page. Please try this tool to check your page structure https://gsnedders.html5.org/outliner/

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/index.html
> +
redundant empty line

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/index.html
> +
redundant empty line

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/index.html
> +</html>
incorrect indent: `<html>` wraps `<body>`

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/style.css
> +} */
remove unused code

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/style.css
> +    width: 810px;
Incorrect width

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/style.css
> +
redundant empty line

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/index.html
> +                    <h1 class="title">Portfolio</h1>
Also, the HTML validator shows you appropriate warnings 
![image](https://user-images.githubusercontent.com/6594800/111918239-380bf500-8a95-11eb-8683-ff7e01e76042.png)

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task2/cv.html
> +            <article class="education">
Please [read this](https://habr.com/ru/post/546994/) article, maybe you will change your mind to use `<article>` here, maybe not :)

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task2/style.css
> +
redundant empty line

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task2/style.css
> +
redundant empty line

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task2/style.css
> +
redundant empty line

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task2/style.css
> +
too many empty lines

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task2/style.css
> +    background: #5c2020fd;
incorrect color ([read this](https://www.w3schools.com/css/css_colors_hex.asp))

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task2/style.css
> +    border: 2px solid #5c2020fd;
incorrect color

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task2/style.css
> +    background-color: #5c2020fd;
incorrect color

2021-03-21 19:55 UTC, danymill commented on homeworks/mariana-dzividzinska/03-html-css/task1/index.html
> +</html>
But if you used some tool, or _emmet_ to generate HTML template, please skip this place, but check other indents

2021-03-21 19:56 UTC, danymill commented
Please note, that you didn't complete the last task (selected on screen) 
![image](https://user-images.githubusercontent.com/6594800/111918990-b6b66180-8a98-11eb-86e8-80fe9cbef499.png)

2021-03-23 17:15 UTC, DzividzinskaM commented
I've already fixed issues

2021-03-25 13:37 UTC, merged