[homework#5] HTML-CSS-CV-3 by Roman Palagniuk
qaprosoft/devlaba01 pull request #49
Opened 2021-03-23 17:12 UTC by RomanPalagniuk

2021-03-24 20:26 UTC, solvd-mmelnyk requested changes
1) крестик неровный, так было задумано?
<img width="491" alt="Screenshot at Mar 24 22-23-24" src="https://user-images.githubusercontent.com/69977904/112378522-b663d380-8cef-11eb-853f-62e502220480.png">

2021-03-24 20:26 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/05-html-css-3/CV.css
> +.mn {
придумай другое названия для класа, а то не ясно что таке mn

2021-03-24 20:26 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/05-html-css-3/CV.html
> +              ></i
тут криво и дальше в этом файле тоже криво
лучше используй <a /> если пустой

2021-03-24 20:26 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/05-html-css-3/CV.html
> +          <div class="card_wrap">
странное название класа
почему card_wrap? тут БЕМ должен быть?

2021-03-24 21:03 UTC, RomanPalagniuk commented on homeworks/roman-palagniuk/05-html-css-3/CV.html
> +              ></i
can't change that. Prettier keeps changing even after I tried to fix every <i> and <a> tag...

2021-03-25 19:27 UTC, solvd-mmelnyk commented
насчёт этого пункта: 
"All elements requiring property changes should be animated (only :hover/:focus states)"

у тебя все анимации на появление тега, а не на ховер. Сделай на ховер и добавь в несколько мест.

2021-03-25 20:55 UTC, solvd-mmelnyk commented
looks good!

2021-03-25 20:55 UTC, merged