[homework#6]-js-basics by Roman Palagniuk
qaprosoft/devlaba01 pull request #80
Opened 2021-04-08 16:26 UTC by RomanPalagniuk

2021-04-09 10:35 UTC, solvd-mmelnyk requested changes
Намного лучше чём предыдущие домашку по стайл гайду! Тут молодец!
по задачам неплохо, но постарайся называть переменные более понятным образом

2021-04-09 10:35 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +function getMiddle(s) {
для меня не ясно что такое s , используй что то более понятное

2021-04-09 10:35 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +      return 0;
в чём логика тут возвращать ноль? думаю лучше тут ошибку вернуть

2021-04-09 10:35 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +function findOdd(A) {
не ясно что такое А

2021-04-11 19:59 UTC, RomanPalagniuk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +function findOdd(A) {
так было в задаче по дефолту. мы делаем решение уже в предоставленном шаблоне. оттуда и 'A', и 'function'. также и в других примерах

2021-04-11 20:01 UTC, RomanPalagniuk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +      return 0;
физический калькулятор возвращает ноль по дефолту

2021-04-11 20:02 UTC, RomanPalagniuk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +function getMiddle(s) {
было в условии

2021-04-12 11:30 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +function getMiddle(s) {
я понимаю, но можно же поменять для читаемости

2021-04-12 11:31 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +      return 0;
хм....
где нашел такую инфу?

2021-04-12 11:31 UTC, solvd-mmelnyk commented on homeworks/roman-palagniuk/06-js-basics/index.js
> +function findOdd(A) {
я понимаю, но можно же поменять для читаемости

2021-04-12 11:31 UTC, merged