[homework#8]-js-basics by Ivashkevich Roman
qaprosoft/devlaba01 pull request #96
Opened 2021-04-12 21:50 UTC by emarf

2021-04-14 16:53 UTC, DmitryMishin requested changes

2021-04-14 16:53 UTC, DmitryMishin commented on homeworks/roman-ivashkevich/08-js-basic/solutions.js
> +    if (typeof obj !== 'object' || obj === null) return null;
let's talk about additional best practices 😉 
The following code will be better:
```javascript
const pluck = (obj, path) => {
  if (typeof obj !== 'object' || obj === null) return null;

  const paths = path.split('.');
  let result = obj;

  for (let i = 0; i < paths.length; i += 1) {
    result = result[paths[i]];
    if (!result) return null;
  }

  return result;
};
```

2021-04-14 16:53 UTC, DmitryMishin commented on homeworks/roman-ivashkevich/08-js-basic/solutions.js
> +    const cloneObj = {};
it's better to use `clonedObj` because right now you're using a verb for a variable

2021-04-14 16:53 UTC, DmitryMishin commented on homeworks/roman-ivashkevich/08-js-basic/solutions.js
> +function solution3() {
There is a bit wrong results
You can try to check socials and you will see that they remove some data if there is some long period
e.g. if it was more than 1 day ago I can write only diff of days: `2 days` without hours

2021-04-14 16:53 UTC, DmitryMishin commented on homeworks/roman-ivashkevich/08-js-basic/solutions.js
> +// task 8
please add link to the task
Also it's a solution for the task 9

2021-04-16 16:37 UTC, danymill requested changes

2021-04-16 16:37 UTC, danymill commented on homeworks/roman-ivashkevich/08-js-basic/solutions.js
> +      Object.entries(el).reduce((acc, [key, value]) => {
do you need `reduce` here? You should use it correctly or replace it with another method

2021-04-18 11:19 UTC, DmitryMishin approved these changes

2021-04-18 11:19 UTC, merged